/*
 * This source file was generated by the Gradle 'init' task
 */
package org.kotlinls

import kotlin.test.Test
import kotlin.test.assertTrue

class AppTest {
  @Test
  fun test() {
    assertTrue { true }
  }
}
